application: profittrillionserver 
version: 1-alpha-2
runtime: python27
api_version: 1
threadsafe: "no"

handlers:
- url: /game/index.html
  static_files: web/index.html
  upload: web/index.html
  
- url: /game/.*
  script: profitserver.app

- url: /
  static_files: web/index.html
  upload: web/index.html
  
- url: /(.+)
  static_files: web/\1
  upload: web/(.+)